config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items,  only: [:index, :show]
  resources :orders, only: [:index, :show]
  resources :users,  only: [:index, :show]
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  has_many :order_items
  has_many :items, through: :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id].to_i)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @items.count %> Items</h1>
    </div>
  </div>
  <div class="row"></div>
  <% @items.each do |item| %>
    <div class="col-sm-3">
      <h5><%= item.name %></h5>
      <%= link_to(image_tag(item.image_url), item_path(item)) %>
      <p>
        <%= item.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row"></div>
  <div class="col-sm-3">
    <h5><%= @item.name %></h5>
    <%= image_tag(@item.image_url) %>
    <p>
      <%= @item.description %>
    </p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Storedom</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
        <a href="/">Items</a>
      </li>
      <li>
        <a href="/users">Users</a>
      </li>
      <li>
        <a href="/orders">Orders</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Storedom</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @orders.count %> Orders</h1>
    </div>
  </div>
  <div class="row"></div>
  <% @orders.each do |order| %>
    <div class="col-sm-12">
      <h2>Order <%= order.id %></h2>
      <h5>Client: <%= order.user.name %></h5>
      <h5>Order Items</h5>
      <% order.items.each_with_index do |item, index| %>
        <p>
          <%= "#{index + 1}. #{item.name}" %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @users.count %> Users</h1>
    </div>
  </div>
  <div class="row"></div>
  <% @users.each do |user| %>
    <div class="col-sm-12">
      <h2>User <%= user.id %></h2>
      <p><strong>Name:</strong> <%= user.name %></p>
      <p><strong>Email:</strong> <%= user.email %></p>
      <h5>Orders</h5>
      <% if user.orders.count > 0 %>
        <% user.orders.each_with_index do |order, index| %>
          <p>
            <%= "#{index + 1}. Order #{order.id}" %>
          </p>
        <% end %>
      <% else %>
        <p>This user doesn't have any orders.</p>
      <% end %>
    </div>
  <% end %>
</div>